### ISSUE TITLE
Common / Combined log format incorrect

### ISSUE THREAD

**Issue by fliespl** [Forza-tng/logparse#1]
Common / Combined require two variabes (or hyphen) identity + user_id.

Your script produces only one.

**Comment by Forza-tng** [comment]
Thanks for the report. I'll take a look at it later this week.

**Comment by Forza-tng** [comment]
> Common / Combined require two variabes (or hyphen) identity + user_id.
> 
> Your script produces only one.

According to https://httpd.apache.org/docs/2.4/logs.html the second field is the `identity` reported by a client's identd service.

I do not believe this check is possible in Caddy, so I think we should hard code the hyphen as the second field. Does that sound reasonable?

There is another discrepancy in the date format as well. Apache states `[day/month/year:hour:minute:second zone]`, but `jq` cannot reliably handle time zones. At the moment logparse therefore assume `UTC-0`. More info on https://jqlang.github.io/jq/manual/#dates

**Comment by fliespl** [comment]
It does, most logs I have worked with have two hypens.

**Comment by Forza-tng** [comment]
I've added the missing hyphen.

https://github.com/Forza-tng/logparse/commit/40dc4c2e3cc5bfc94f4232b6cad48374a1a07c9d
